compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: /home/work/conan/llama3_finetuning/dpo/ds_config.json
  # deepspeed_multinode_launcher: standard
  # offload_optimizer_device: cpu
  # offload_param_device: cpu
  # zero_stage: 3
  zero3_init_flag: true
  # zero3_save_16bit_model: true
distributed_type: DEEPSPEED # MULTI_GPU #
downcast_bf16: no
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
