#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/g3moe/modular_g3moe.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_g3moe.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 Google Inc. HuggingFace Inc. team. All rights reserved.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import warnings
from typing import Optional, Union, Dict, Any

from transformers.configuration_utils import PretrainedConfig, layer_type_validation
from transformers.modeling_rope_utils import rope_config_validation
from transformers.utils import logging
from transformers.models.siglip import SiglipVisionConfig


logger = logging.get_logger(__name__)


class G3MoETextConfig(PretrainedConfig):
    r"""
    This is the configuration class to store the configuration of a [`G3MoETextModel`]. It is used to instantiate an G3MoEText
    model according to the specified arguments, defining the model architecture. Instantiating a configuration with the
    defaults will yield a similar configuration to that of the G3MoEText-7B.
    e.g. [google/g3moe_text-7b](https://huggingface.co/google/g3moe_text-7b)
    Configuration objects inherit from [`PretrainedConfig`] and can be used to control the model outputs. Read the
    documentation from [`PretrainedConfig`] for more information.
    Args:
        vocab_size (`int`, *optional*, defaults to 262208):
            Vocabulary size of the G3MoEText model. Defines the number of different tokens that can be represented by the
            `inputs_ids` passed when calling [`G3MoETextModel`]
        hidden_size (`int`, *optional*, defaults to 2304):
            Dimension of the hidden representations.
        intermediate_size (`int`, *optional*, defaults to 9216):
            Dimension of the MLP representations.
        num_hidden_layers (`int`, *optional*, defaults to 26):
            Number of hidden layers in the Transformer decoder.
        num_attention_heads (`int`, *optional*, defaults to 8):
            Number of attention heads for each attention layer in the Transformer decoder.
        num_key_value_heads (`int`, *optional*, defaults to 4):
            This is the number of key_value heads that should be used to implement Grouped Query Attention. If
            `num_key_value_heads=num_attention_heads`, the model will use Multi Head Attention (MHA), if
            `num_key_value_heads=1` the model will use Multi Query Attention (MQA) otherwise GQA is used. When
            converting a multi-head checkpoint to a GQA checkpoint, each group key and value head should be constructed
            by meanpooling all the original heads within that group. For more details checkout [this
            paper](https://arxiv.org/pdf/2305.13245.pdf). If it is not specified, will default to
            `num_attention_heads`.
        head_dim (`int`, *optional*, defaults to 256):
            The attention head dimension.
        kv_lora_rank (`int`, *optional*, defaults to 512):
            LoRA rank for key/value projections.
        q_lora_rank (`int`, *optional*, defaults to 1536):
            LoRA rank for query projections.
        qk_rope_head_dim (`int`, *optional*, defaults to 64):
            Head dimension for RoPE in Q/K projections.
        n_shared_experts (`int`, *optional*, defaults to 1):
            Number of shared experts in MoE.
        n_routed_experts (`int`, *optional*, defaults to 256):
            Number of routed experts in MoE.
        routed_scaling_factor (`float`, *optional*, defaults to 2.5):
            Scaling factor for routed experts.
        n_group (`int`, *optional*, defaults to 8):
            Number of groups for expert routing.
        topk_group (`int`, *optional*, defaults to 4):
            Number of top groups for expert routing.
        num_experts_per_tok (`int`, *optional*, defaults to 8):
            Number of experts per token (top-k).
        first_k_dense_replace (`int`, *optional*, defaults to 3):
            Number of initial layers to use dense MLP instead of MoE.
        norm_topk_prob (`bool`, *optional*, defaults to True):
            Whether to normalize top-k routing probabilities.
        hidden_activation (`str` or `function`, *optional*, defaults to "gelu_pytorch_tanh"):
            The non-linear activation function (function or string) in the decoder. Will default to "gelu_pytorch_tanh"
            if not specified. "gelu_pytorch_tanh" uses an approximation of the "gelu" activation function.
        max_position_embeddings (`int`, *optional*, defaults to 131072):
            The maximum sequence length that this model might ever be used with.
        initializer_range (`float`, *optional*, defaults to 0.02):
            The standard deviation of the truncated_normal_initializer for initializing all weight matrices.
        rms_norm_eps (`float`, *optional*, defaults to 1e-06):
            The epsilon used by the rms normalization layers.
        use_cache (`bool`, *optional*, defaults to `True`):
            Whether or not the model should return the last key/values attentions (not used by all models). Only
            relevant if `config.is_decoder=True`.
        pad_token_id (`int`, *optional*, defaults to 0):
            Padding token id.
        eos_token_id (`int`, *optional*, defaults to 1):
            End of stream token id.
        bos_token_id (`int`, *optional*, defaults to 2):
            Beginning of stream token id.
        tie_word_embeddings (`bool`, *optional*, defaults to `True`):
            Whether to tie weight embeddings
        rope_theta (`float`, *optional*, defaults to 1000000.0):
            The base period of the RoPE embeddings.
        attention_bias (`bool`, *optional*, defaults to `False`):
            Whether to use a bias in the query, key, value and output projection layers during self-attention.
        attention_dropout (`float`, *optional*, defaults to 0.0):
            The dropout ratio for the attention probabilities.
        query_pre_attn_scalar (`float`, *optional*, defaults to 256):
            Scaling factor used on the attention scores
        sliding_window (`int`, *optional*, defaults to 4096):
            Size of the sliding window attention.
        final_logit_softcapping (`float`, *optional*):
            Scaling factor when applying tanh softcapping on the logits.
        attn_logit_softcapping (`float`, *optional*):
            Scaling factor when applying tanh softcapping on the attention scores.
        cache_implementation (`str`, *optional*, defaults to "hybrid"):
            The cache type to be used with `generate`.
        rope_scaling (`Dict`, *optional*):
            Dictionary containing the scaling configuration for the RoPE embeddings used in gloabl attention. NOTE: if you apply new rope type
            and you expect the model to work on longer `max_position_embeddings`, we recommend you to update this value
            accordingly.
            Expected contents:
                `rope_type` (`str`):
                    The sub-variant of RoPE to use. Can be one of ['default', 'linear', 'dynamic', 'yarn', 'longrope',
                    'llama3'], with 'default' being the original RoPE implementation.
                `factor` (`float`, *optional*):
                    Used with all rope types except 'default'. The scaling factor to apply to the RoPE embeddings. In
                    most scaling types, a `factor` of x will enable the model to handle sequences of length x *
                    original maximum pre-trained length.
                `original_max_position_embeddings` (`int`, *optional*):
                    Used with 'dynamic', 'longrope' and 'llama3'. The original max position embeddings used during
                    pretraining.
                `attention_factor` (`float`, *optional*):
                    Used with 'yarn' and 'longrope'. The scaling factor to be applied on the attention
                    computation. If unspecified, it defaults to value recommended by the implementation, using the
                    `factor` field to infer the suggested value.
                `beta_fast` (`float`, *optional*):
                    Only used with 'yarn'. Parameter to set the boundary for extrapolation (only) in the linear
                    ramp function. If unspecified, it defaults to 32.
                `beta_slow` (`float`, *optional*):
                    Only used with 'yarn'. Parameter to set the boundary for interpolation (only) in the linear
                    ramp function. If unspecified, it defaults to 1.
                `short_factor` (`List[float]`, *optional*):
                    Only used with 'longrope'. The scaling factor to be applied to short contexts (<
                    `original_max_position_embeddings`). Must be a list of numbers with the same length as the hidden
                    size divided by the number of attention heads divided by 2
                `long_factor` (`List[float]`, *optional*):
                    Only used with 'longrope'. The scaling factor to be applied to long contexts (<
                    `original_max_position_embeddings`). Must be a list of numbers with the same length as the hidden
                    size divided by the number of attention heads divided by 2
                `low_freq_factor` (`float`, *optional*):
                    Only used with 'llama3'. Scaling factor applied to low frequency components of the RoPE
                `high_freq_factor` (`float`, *optional*):
                    Only used with 'llama3'. Scaling factor applied to high frequency components of the RoPE
        rope_local_base_freq (float, *optional*, defaults to 10000.0):
            The base period of the RoPE embeddings for local attention.
        sliding_window_pattern (`int`, *optional*, defaults to 6):
            Pattern for the sliding window attention.

    ```python
    >>> from transformers import G3MoETextModel, G3MoETextConfig
    >>> # Initializing a G3MoEText g3moe_text-7b style configuration
    >>> configuration = G3MoETextConfig()
    >>> # Initializing a model from the g3moe_text-7b style configuration
    >>> model = G3MoETextModel(configuration)
    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```
        rope_local_base_freq (float, *optional*, defaults to 10000.0):
            The base period of the RoPE embeddings for local attention.
        sliding_window_pattern (`int`, *optional*, defaults to 6):
            Pattern for the sliding window attention.
    """

    model_type = "g3moe_text"
    keys_to_ignore_at_inference = ["past_key_values"]
    base_model_tp_plan = {
        "layers.*.self_attn.q_proj": "colwise",
        "layers.*.self_attn.k_proj": "colwise",
        "layers.*.self_attn.v_proj": "colwise",
        "layers.*.self_attn.o_proj": "rowwise",
        "layers.*.experts": "gater",
        "layers.*.router": "ep_router",
        "layers.*.experts.*.gate_proj": "grouped_gemm",
        "layers.*.experts.*.gate_proj_bias": "grouped_gemm",
        "layers.*.experts.*.up_proj": "grouped_gemm",
        "layers.*.experts.*.up_proj_bias": "grouped_gemm",
        "layers.*.experts.*.down_proj": "grouped_gemm",
        "layers.*.experts.*.down_proj_bias": "grouped_gemm",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        "norm": (["hidden_states"], ["hidden_states"]),
    }

    def __init__(
        self,
        vocab_size=262_208,
        hidden_size=2304,
        intermediate_size=9216,
        num_hidden_layers=26,
        num_attention_heads=8,
        num_key_value_heads=4,
        head_dim=256,
        kv_lora_rank=512,
        q_lora_rank=1536,
        qk_rope_head_dim=64,
        n_shared_experts=1,
        n_routed_experts=256,
        routed_scaling_factor=2.5,
        topk_group=4,
        n_group=8,
        num_experts_per_tok=8,
        first_k_dense_replace=3,
        norm_topk_prob=True,
        router_aux_loss_coef=5e-3,
        router_jitter_noise=0.01,
        input_jitter_noise=0.01,
        router_z_loss_coef=0.0001,
        router_entropy_coef=0.003,
        usage_uniformity_coef=0.001,
        ema_alpha=0.99,
        balancing_strength=0.01,
        ortho_strength=1.0,
        ortho_loss_coef=0.01,
        specialization_strength=0.01,
        gslb_coef=0.05,
        lb_l2_coef=0.5,
        lb_cv_coef=0.2,
        lb_entropy_floor_coef=0.0,
        lb_topk_l2_coef=1.0,
        lb_topk_cv_coef=0.5,
        lb_bias_to_hn=True,
        lb_bias_scale=0.1,
        router_dim=128,
        freeze_shared_experts=True,
        hidden_activation="gelu_pytorch_tanh",
        max_position_embeddings=131_072,
        initializer_range=0.02,
        rms_norm_eps=1e-6,
        use_cache=True,
        pad_token_id=0,
        eos_token_id=1,
        bos_token_id=2,
        tie_word_embeddings=True,
        rope_theta=1_000_000.0,
        attention_bias=False,
        attention_dropout=0.0,
        query_pre_attn_scalar=256,
        sliding_window=4096,
        layer_types=None,
        final_logit_softcapping=None,
        attn_logit_softcapping=None,
        cache_implementation="hybrid",
        rope_scaling=None,
        rope_local_base_freq=10_000.0,
        sliding_window_pattern=6,
        # 하이브리드 positional embedding 관련 추가 인자
        no_rope_layers=None,
        no_rope_layer_interval: int = 0,
        use_sliding_window=False,
        attn_implementation="eager",
        **kwargs,
    ):
        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )
        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.head_dim = head_dim
        self.num_key_value_heads = num_key_value_heads
        self.kv_lora_rank = kv_lora_rank
        self.q_lora_rank = q_lora_rank
        self.qk_rope_head_dim = qk_rope_head_dim
        self.n_shared_experts = n_shared_experts
        self.n_routed_experts = n_routed_experts
        self.routed_scaling_factor = routed_scaling_factor
        self.n_group = n_group
        self.topk_group = topk_group
        self.num_experts_per_tok = num_experts_per_tok
        self.first_k_dense_replace = first_k_dense_replace
        self.norm_topk_prob = norm_topk_prob
        self.router_aux_loss_coef = router_aux_loss_coef
        self.router_jitter_noise = router_jitter_noise
        self.input_jitter_noise = input_jitter_noise
        self.router_z_loss_coef = router_z_loss_coef
        self.router_dim = router_dim
        # Additional router regularizers to combat expert collapse
        self.router_entropy_coef = router_entropy_coef
        self.usage_uniformity_coef = usage_uniformity_coef
        self.sliding_window_pattern = sliding_window_pattern
        self.rope_local_base_freq = rope_local_base_freq
        self.freeze_shared_experts = freeze_shared_experts
        self.ema_alpha = ema_alpha
        self.balancing_strength = balancing_strength
        self.ortho_strength = ortho_strength
        self.ortho_loss_coef = ortho_loss_coef
        self.specialization_strength = specialization_strength
        self.gslb_coef = gslb_coef
        self.lb_l2_coef = lb_l2_coef
        self.lb_cv_coef = lb_cv_coef
        self.lb_entropy_floor_coef = lb_entropy_floor_coef
        self.lb_topk_l2_coef = lb_topk_l2_coef
        self.lb_topk_cv_coef = lb_topk_cv_coef
        self.lb_bias_to_hn = lb_bias_to_hn
        self.lb_bias_scale = lb_bias_scale
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.attention_bias = attention_bias
        self.attention_dropout = attention_dropout
        self.hidden_activation = hidden_activation
        self.query_pre_attn_scalar = query_pre_attn_scalar
        self.sliding_window = sliding_window
        self.cache_implementation = cache_implementation
        self.rope_local_base_freq = rope_local_base_freq
        self.sliding_window_pattern = sliding_window_pattern
        self.final_logit_softcapping = final_logit_softcapping
        self.attn_logit_softcapping = attn_logit_softcapping
        self.layer_types = layer_types
        
        self.rope_scaling = rope_scaling
        self.attn_implementation = attn_implementation
        self._attn_implementation = attn_implementation

        # 하이브리드 positional embedding 패턴 생성 (smollm3 스타일)
        if no_rope_layers is None:
            self.no_rope_layers = [
                int((layer_idx + 1) % no_rope_layer_interval == 0) if no_rope_layer_interval > 0 else 0
                for layer_idx in range(num_hidden_layers)
            ]
        else:
            self.no_rope_layers = no_rope_layers
        self.no_rope_layer_interval = no_rope_layer_interval
        # layer_types 자동 생성
        self._sliding_window_pattern = kwargs.get("sliding_window_pattern", 6)
        if layer_types is None:
            layer_types = []
            for layer_idx in range(num_hidden_layers):
                has_nope = self.no_rope_layers[layer_idx]
                if use_sliding_window and sliding_window is not None and not has_nope:
                    layer_types.append("sliding_attention")
                else:
                    layer_types.append("full_attention")
        self.layer_types = layer_types
        layer_type_validation(self.layer_types)

        self.use_sliding_window = use_sliding_window
        # layer_types validation 등 추가
        # layer_type_validation(self.layer_types)  # 필요시 함수 정의
        # rope config validation
        if self.rope_scaling is not None and "type" in self.rope_scaling:
            self.rope_scaling["rope_type"] = self.rope_scaling["type"]
        rope_config_validation(self)
        
    @property
    def sliding_window_pattern(self):
        warnings.warn(
            "The `sliding_window_pattern` attribute is deprecated and will be removed in v4.55.0.",
            FutureWarning,
        )
        return self._sliding_window_pattern

    @sliding_window_pattern.setter
    def sliding_window_pattern(self, value):
        self._sliding_window_pattern = value

class G3MoEConfig(PretrainedConfig):
    r"""
    This is the configuration class to store the configuration of a [`G3MoEForConditionalGeneration`]. It is used to instantiate an
    G3MoEForConditionalGeneration according to the specified arguments, defining the model architecture. Instantiating a configuration
    with the defaults will yield a similar configuration to that of the PaliGemma-2B.

    e.g. [google/g3moe-4b](https://huggingface.co/google/g3moe-4b)

    Configuration objects inherit from [`PretrainedConfig`] and can be used to control the model outputs. Read the
    documentation from [`PretrainedConfig`] for more information.

    Args:
        text_config (`Union[G3MoETextConfig, dict]`, *optional*):
            The config object of the text backbone.
        vision_config (`Union[SiglipVisionConfig, dict]`,  *optional*):
            Custom vision config or dict.
        mm_tokens_per_image (`int`, *optional*, defaults to 256):
            The number of tokens per image embedding.
        boi_token_index (`int`, *optional*, defaults to 255999):
            The begin-of-image token index to wrap the image prompt.
        eoi_token_index (`int`, *optional*, defaults to 256000):
            The end-of-image token index to wrap the image prompt.
        image_token_index (`int`, *optional*, defaults to 262144):
            The image token index to encode the image prompt.
        initializer_range (`float`, *optional*, defaults to 0.02):
            The standard deviation of the truncated_normal_initializer for initializing all weight matrices.


    Example:

    ```python
    >>> from transformers import G3MoEForConditionalGeneration, G3MoEConfig, SiglipVisionConfig, G3MoETextConfig

    >>> # Initializing a Siglip-like vision config
    >>> vision_config = SiglipVisionConfig()

    >>> # Initializing a G3MoE Text config
    >>> text_config = G3MoETextConfig()

    >>> # Initializing a G3MoE g3moe-4b style configuration
    >>> configuration = G3MoEConfig(vision_config, text_config)

    >>> # Initializing a model from the g3moe-4b style configuration
    >>> model = G3MoETextConfig(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "g3moe"
    attribute_map = {
        "image_token_id": "image_token_index",
        "boi_token_id": "boi_token_index",
        "eoi_token_id": "eoi_token_index",
    }
    sub_configs = {
        "text_config": G3MoETextConfig,
        "vision_config": SiglipVisionConfig,
    }

    def __init__(
        self,
        text_config: Optional[Union[G3MoETextConfig, Dict[str, Any]]] = None,
        vision_config: Optional[Union[SiglipVisionConfig, Dict[str, Any]]] = None,
        mm_tokens_per_image: int = 256,
        boi_token_index: int = 255_999,
        eoi_token_index: int = 256_000,
        image_token_index: int = 262_144,
        initializer_range: float = 0.02,
        **kwargs,
    ):
        if text_config is None:
            text_config = G3MoETextConfig()
            logger.info("text_config is None, using default G3MoETextConfig vision config.")
        elif isinstance(text_config, dict):
            text_config.update(kwargs)
            text_config = G3MoETextConfig(**text_config)

        if isinstance(vision_config, dict):
            vision_config = SiglipVisionConfig(**vision_config)
        else:
            vision_config = SiglipVisionConfig()
            logger.info(
                "vision_config is None or incompatible with G3MoEVisionConfig intialization. G3MoE will be limited "
                "to text tasks."
            )

        self.text_config = text_config
        self.vision_config = vision_config
        self.mm_tokens_per_image = mm_tokens_per_image
        self.boi_token_index = boi_token_index
        self.eoi_token_index = eoi_token_index
        self.image_token_index = image_token_index
        self.initializer_range = initializer_range

        super().__init__(**kwargs)


__all__ = ["G3MoEConfig", "G3MoETextConfig"]
